# Generated by Django 2.0.2 on 2018-02-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(editable=False, verbose_name='Number')),
                ('bid', models.IntegerField(editable=False, verbose_name='Battery ID')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'batteries',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.SlugField(unique=True, verbose_name='Vehicle ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='battery',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='vehicles.Vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='battery',
            unique_together={('bid', 'vehicle'), ('number', 'vehicle')},
        ),
    ]
